image: ubuntu

before_build:
  - sh: sudo apt-get update
  - sh: sudo apt-get install -y fakeroot dos2unix

build_script:
  - sh: dos2unix /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/config
  - sh: chmod 755 /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/config
  - sh: dos2unix /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/postinst
  - sh: chmod 755 /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/postinst
  - sh: dos2unix /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/postrm
  - sh: chmod 755 /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/postrm
  - sh: dos2unix /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/etc/cron.d/masked-emails
  - sh: dos2unix /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/etc/init.d/masked-emails
  - sh: fakeroot dpkg --build /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh

artifacts:
  - path: '**\*deb'
    type: file

deploy:
  provider: AzureBlob
  storage_account_name: masked
  storage_access_key:
    secure: ZC0PpKsfUYg3ffTy+l2I4y6tluKtxMuovqxehGwpb2WoH5MRJaB5jGwfVD0g6BdLwVnO+SwQU5smBrt9kluDQwBHFjCafOAxpPxigv61hf/zazMjwIWckcE3sF57lcn2
  container: debian
  artifact: masked-emails-pwsh.deb
  unzip: false
  set_content_type: false