image: ubuntu

before_build:
  - pwsh: sudo apt-get update
  - pwsh: sudo apt-get install -y fakeroot

build_script:
  - pwsh: chmod 755 /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/config
  - pwsh: chmod 755 /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/postinst
  - pwsh: chmod 755 /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh/DEBIAN/postrm
  - pwsh: fakeroot dpkg --build /home/appveyor/projects/masked-emails-pwsh/masked-emails-pwsh

artifacts:
  - path: '**\*deb'
    type: file

deploy:
  provider: AzureBlob
  storage_account_name: masked
  storage_access_key:
    secure: xgb9tBmhTWgMpmwhpauTdDsVrSezLCXBp9EWwN9rNvAIdSMIEbBwpHmnjushM5oex5ipUwDK9f8+VIZs3QIp12KFMeTDmtLW2tFcycSl3tUK3Kf4+sPGvGene6ApQvHu
  container: debian
  artifact: masked-emails-pwsh.deb
  unzip: false
  set_content_type: false